apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-mq		
  namespace: cp4i
spec:
  channel: v2.0
  name: ibm-mq		
  source: ibm-operator-catalog
  sourceNamespace: openshift-marketplace