apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: datapower-operator		
  namespace: cp4i
spec:
  channel: v1.6
  name: datapower-operator		
  source: ibm-operator-catalog
  sourceNamespace: openshift-marketplace